### ISSUE TITLE
Cockpit door not showing correctly/misplaced idk

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#127] opened 2019-10-11 18:28 UTC
**Describe the bug**
Door is kinda hovering 

**To Reproduce**
Just leave the cockpit and look at it from the galley

**Expected behavior**
should be kinda solid 

**Screenshots**
![B7879 - 2019-10-11 20 26 33](https://user-images.githubusercontent.com/46034843/66675402-8e042880-ec65-11e9-9469-b01d4523b94e.png)

**Desktop (please complete the following information):**
 - OS: W10
 - X-Plane version 11.36
 - Version 1.4.0

**Additional context**

**Comment by aeroniemi** [comment] 2019-10-11 20:55
door needs to open once completed - will be fixed in the 1.4.x run

**Comment by magknight1** [comment] 2019-11-04 04:08
Position of the cabian alley leading to cockpit was the cause of the issue.

**Closed by magknight1** 2019-11-04 04:08 UTC
Labels: bug, modelling
