### ISSUE TITLE
Have a Manual Descent line on Navigation Display

### ISSUE THREAD

**Issue by SamuelAviatron** [magknight/787aviatorsTracker#341] opened 2020-05-06 07:21 UTC
**Is your feature request related to a problem? Please describe.**
I am always fustrated with the VNAV Descent not working properly. Without the descent line, It is very hard to manually descent. Since you don't know where you will end up at. This is especially annoying when flying on Vatsim and getting vectors. 

**Describe the solution you'd like**
You would add a simple line like the 787 navigation line below. This would greatly help with manual descent when VNAV descent doesn't work properly. 
![image](https://user-images.githubusercontent.com/42186097/81147577-9517be80-8f48-11ea-8f4b-55370faf9f5e.png)

**Comment by aeroniemi** [comment] 2020-05-10 15:48
duplicate of #256

**Closed by aeroniemi** 2020-05-10 15:48 UTC
Labels: duplicate
