### ISSUE TITLE
Plane not following the route heading

### ISSUE THREAD

**Issue by AviationGoalie** [magknight/787aviatorsTracker#202] opened 2019-10-28 21:51 UTC
So today I streamed the magknight 787 on AviationGoalie on twitch. Watch my latest stream and you can see how the plane is turning way before the curve to the runway. And that caused me to not being able to land.

IF NOT! Whehn i tried to land at KMIA the plane didnt follow the turn in to the airport before the runway. It like cutted it in half and then I got way off. So i needed to restart the landing! 

This is really annoying, please if you see this can you guys fix it maybe?

**Comment by aeroniemi** [comment] 2019-10-29 23:55
duplicate of #152

**Closed by aeroniemi** 2019-10-29 23:55 UTC
Labels: triage
