### ISSUE TITLE
Captain's Armrest

### ISSUE THREAD

**Issue by tailwest** [magknight/787aviatorsTracker#432] opened 2020-08-10 14:57 UTC
**Describe the bug**
Armrest not moving. Unidentified object is moving instead

**To Reproduce**
Try to move the armrest up and down

**Expected behavior**
Armrest should mould

**Screenshots**
![image](https://user-images.githubusercontent.com/62467289/89796546-75d59200-db32-11ea-86d2-e357134b1c60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5b17
 - Version v1.6.0-cygnus5

**Comment by aeroniemi** [comment] 2020-08-10 15:04
duplicate of #418

**Closed by aeroniemi** 2020-08-10 15:04 UTC
Labels: triage
