### ISSUE TITLE
Cargo door seams to keep rotating

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#194] opened 2019-10-24 12:28 UTC
**Describe the bug**
The door will keep rotating indefinitely by the looks of it.

**To Reproduce**
Honestly not sure what I did to do this, I was testing Ground Handling and I noticed this happening. All I did was open the door using the EFIS then close it through EFIS.

**Expected behavior**
It should just close.

**Screenshots**
https://www.youtube.com/watch?v=tJydKb2lz8w&feature=youtu.be

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.40b1
 - Version 1.4.0b5

**Comment by aeroniemi** [comment] 2019-10-24 15:15
i can't reproduce that happening, but i did see that the cargo door was closing instantly, and i've fixed that. Maybe the two things are somehow related

**Closed** 2019-11-03 23:02 UTC
Labels: bug, maybe fixed
