### ISSUE TITLE
EFB "Spill-light" Illumination

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#245] opened 2019-12-23 21:01 UTC
**Constant Bright Spot Light on EFB during night flight**
See photo When you turn down flight deck / panel rheostats the light continues to shine brightly! Aeroniemi fixed in beta7 but it came back in RC-1 and RC-2

**To Reproduce**
Setup a night situation on ground or in flight and turn down all dimmers. The EFB "overhead area light" is way too bright and no way to adjust.

**Expected behavior**
Either reduce the illumination by 50% or attached to a dimmer/rheostat so we can control

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - X-Plane version 11.41r1
 - Version 1.40.RC-2
![787_9-efb](https://user-images.githubusercontent.com/56449761/71380499-4adb0580-2584-11ea-8fb9-31eb772e2565.png)

**Additional context**

**Comment by aeroniemi** [comment] 2019-12-24 20:06
duplicate of #236

**Closed by aeroniemi** 2019-12-24 20:06 UTC
Labels: triage
