### ISSUE TITLE
Doubled touchdown sounds

### ISSUE THREAD

**Issue by Sdozer** [magknight/787aviatorsTracker#197] opened 2019-10-26 01:13 UTC
This was catched at beta1, but if you guys haven't touch this part this maybe occuring until now, sorry for the delay

Video: https://drive.google.com/open?id=1uz794cuLYEQVLHAFETjIA9Ntc4JVNNKc

**Describe the bug**
I'm getting touchdown sounds playing twice, wich could be normal since the wheel touches the ground twice, I think the bug is the way that the sounds are playing, we have a sudden stop of the first and then it plays again, maybe there is a way to smoothen this transitions

**To Reproduce**
Steps to reproduce the behavior: try to perform a smoothest landing you can to get the main gear touches the ground more than once

**Expected behavior**
You'll hear the touchdown sound play both times but with an abrupt transition between them

**Screenshots**
Video above.

**Desktop (please complete the following information):**
 - OS: [Win 8.1]
 - X-Plane version [11.36]
 - Version [Mag 1.4b1]

**Additional context**

**Comment by OldGroof** [comment] 2019-11-02 16:02
I haven't experienced this in my flights but I think it is just X-Plane's and FMOD's system of registering touch downs messing up.

**Comment by audiobirdxp** [comment] 2019-11-19 16:45
Yes it's a rather annoying issue that can occur with sloped runways. Currently there is no really satisfying solution except for programming custom touchdown refs. I tried using different sources of data from the amount and rate of gear compression to the usual "on ground" datarefs but it stays finnicky. It should be better in the current version tho as I usually have sloped runways on and couldn't reproduce it except for purposefully slamming the nose gear up and down repeatedly (which gets you fired so don't do it ;) .Closing for now - please reopen if it persists in an annoying wway.

**Closed by audiobirdxp** 2019-11-19 16:45 UTC
Labels: bug, question
