### ISSUE TITLE
Clock button not working

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#446] opened 2020-08-11 03:25 UTC
**Describe the bug**
clock button does not start the timer

**To Reproduce**
click clock button

**Expected behavior**
should start timer

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6

**Comment by aeroniemi** [comment] 2020-08-11 08:38
duplicate of #421

**Closed by aeroniemi** 2020-08-11 08:38 UTC
Labels: triage
