### ISSUE TITLE
Accuracy of green climb/descent arc on ND

### ISSUE THREAD

**Issue by fafaldo** [magknight/787aviatorsTracker#691] opened 2022-02-09 08:44 UTC
**Describe the bug**
The newly added green 'expected TOC/TOD' green arc has very low accuracy. Don't know what data it is calculated on, but something is clearly miscalculated. Please see attached screenshot for current flight parameters. All these (GS, V/S) were constant for at least 10-20 seconds before screenshot was taken so I wouldn't blame it on one of these values changing. 
According to my simple calculations, having a GS=274kt, V/S=500fpm I would expect my descent to 7000ft to end in approx. 10nm. Instead it shows more than 30nm. 
Another strange thing is that the closer we get to the desired altitude, the better the estimation is - the arc appears to be pointing to a point closer and closer the lower I get. Please note I understand the aircraft is moving so I am not talking about the relative distance from the AC to the arc (which will always get smaller) but an "absolute" position of the end of descent in space. 
In this example, at 7200ft it would probably show the arc being just after the DB529 waypoint (and that is correct based on my calculations) but at 8200ft it's pointing to somewhere even further than DB513.

**To Reproduce**
Just fly a while in V/S AP mode,

**Expected behaviour**
Green arc is stable and reliable, and given constant flight parameters it should always point to the same point in space.

**Screenshots**
![Capture-calc](https://user-images.githubusercontent.com/63355317/153157796-225da0ac-1f0f-4797-8c3e-9eaba62e9b54.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.55
 - Version 1.7.20-beta10

**Comment by aeroniemi** [comment] 2022-02-10 13:56
i think the issue is that it didn't convert from ms-1 to kts properly, seems to be fixed now

**Closed as completed** 2022-02-10 13:58 UTC
Labels: bug
