### ISSUE TITLE
Plane does not capture ILS

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#187] opened 2019-10-24 08:52 UTC
**Describe the bug**
Flying the ILS runway 23 into YYZ the aircraft remained one half dot right of the localizer on final. The aircraft said it had captured the ILS but it never did. I had to hand fly the approach. 

**To Reproduce**
Try to fly an ILS. 

**Expected behavior**
The aircraft should lock onto and follow the ILS 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - X-Plane version Latest stable
 - Version 1.40 B4

**Additional context**
not using experimental flight model

**Comment by matthew007800** [comment] 2019-10-24 11:12
Unable to reproduce

**Comment by aeroniemi** [comment] 2019-10-24 11:16
duplicate of #152

**Closed by aeroniemi** 2019-10-24 11:16 UTC
Labels: bug
