### ISSUE TITLE
ILS LOC & AP disconnect sound

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#201] opened 2019-10-28 19:45 UTC
**Describe the bug**
KIAD RWY 19L -   Plane would not hold the LOC, plane sat left or right of the localiser.
Also, No AP Disconnect sound, when using the AP Disconnect bar on the AP
**To Reproduce**
ILS RWY 19L

**Expected behavior**
Follow runway centerline

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.36r2]
 - Version [e.g. 1.2.0B5]

**Additional context**

**Comment by aeroniemi** [comment] 2019-10-29 23:55
duplicate of #152

**Closed by aeroniemi** 2019-10-29 23:55 UTC
Labels: triage
