### ISSUE TITLE
OPEN THE CDU LIKE A WINDOW / THE LEFT SIDE GAS LEVER IS LOCKED

### ISSUE THREAD

**Issue by cherrymx89** [magknight/787aviatorsTracker#227] opened 2019-12-11 06:12 UTC
- OPEN THE CDU LIKE A WINDOW
([AERO787 INFO]: [LUA]: the "cduAPopup" key was clicked: 65
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
[AERO787 INFO]: [LUA]: the "cduAPopup" key was clicked: 77
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
[AERO787 INFO]: [LUA]: the "cduAPopup" key was clicked: 88
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
[INFORMATION AERO787]: [LUA]: "cduAPopup" command
WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_multisample WGL_ARB_pbuffer WGL_ARB_pixel_format WGL_ARB_pixel_format_float WGL_ARB_render_texture WGL_ATI_pixel_format_float WGL_EXT_colorspace WGL_EXT_create_context_es_profile WGL_EXT_create_context_es2_profile WGL_EXT_extensions_string WGL_EXT_framebuffer_sRGB WGL_EXT_pixel_format_packed_float WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_NVX_DX_interop WGL_NV_DX_interop WGL_NV_DX_interop2 WGL_NV_copy_image WGL_NV_delay_before_swap WGL_NV_float_buffer WGL_NV_multisample_coverage WGL_NV_multigpu_context WGL_NV_render_depth_texture WGL_NV_render_texture_rectangle
[AERO787 ERROR]: error calling the command controller: C ++ exception
[AERO787 ERROR]: Command: sim / FMS / CDU_popout
[AERO787 ERROR]: Error handling context window mouse event: C ++ exception
- == {This application has been blocked!} == -)

- IN B787-9 1.4.0 RC1, THE LEFT SIDE GAS LEVER IS LOCKED IN THE CENTER, DOES NOT MOVE. like in the image
![B7879 - 2019-12-11 12 06 56 AM](https://user-images.githubusercontent.com/58763366/70595911-29ecda80-1baa-11ea-9b60-7f5f4d618803.png)

- B787-9 rc1, the left engine does not start completely when it reaches 41.0 n2 turns off

**Comment by aeroniemi** [comment] 2019-12-24 20:03
Please attatch the full log - it'll contain other useful data
I'd assume the throttle lever issue is caused by a incorrect joystick configuration - check/reassign it
left engine is probably not starting as throttle lever is not at idle (fuel injection condition)

**Closed** 2020-01-11 13:54 UTC
Labels: question
