### ISSUE TITLE
1.6 Des Now does not work

### ISSUE THREAD

**Issue by jengle53** [magknight/787aviatorsTracker#486] opened 2020-09-22 17:19 UTC
**Describe the bug**
Select Descend Now from the VNAV page 3 - does not descend.  Speed reduces, but no descent.

**To Reproduce**
select Des Now from VNAV page 3

**Expected behavior**
Start early descent to intercept descent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - X-Plane version 11.50
 - Version 1.6 current beta

**Additional context**

**Comment by aeroniemi** [comment] 2022-03-21 00:20
duplicate of #657

**Closed by aeroniemi** 2022-03-21 00:20 UTC
Labels: bug, laminar
