### ISSUE TITLE
COMM button on Captain's MFD not working

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#439] opened 2020-08-11 02:51 UTC
**Describe the bug**
COMM Button for Captain's MFD does not working after the new cockpit. 

**To Reproduce**
Launch X-Plane, load MK787 with new cockpit, start plane, click COMM on Captn's MFD control panel. 

**Expected behavior**
Should bring up COMM page if the display is clear. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6 I think...

**Comment by aeroniemi** [comment] 2020-08-11 08:40
duplicate of #433

**Closed by aeroniemi** 2020-08-11 08:40 UTC
Labels: triage
