### ISSUE TITLE
Left Flaperon stick up a little

### ISSUE THREAD

**Issue by OldGroof** [magknight/787aviatorsTracker#96] opened 2019-09-01 17:20 UTC
**Describe the bug**
When in straight and level flying, with AP on, the left flaperon is always slightly 'up'.

**To Reproduce**
Fly with AP on, straight and level.

**Expected behavior**
It should be flat like the right one.

**Screenshots**
![image](https://user-images.githubusercontent.com/39658757/64079861-0da4ec00-cce5-11e9-856c-fffd1f8e9ca5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.36
 - Version 1.3.8

**Additional context**

**Comment by aeroniemi** [comment] 2019-09-01 17:51
Duplicate of #75

**Comment by aeroniemi** [comment] 2019-09-01 19:21
Resolved in 1.3.9

**Closed by aeroniemi** 2019-09-01 19:21 UTC
Labels: duplicate
