### ISSUE TITLE
EFB Issues 

### ISSUE THREAD

**Issue by brownbear118** [magknight/787aviatorsTracker#142] opened 2019-10-12 22:23 UTC
**Describe the bug**
EFB not letting me select runway on Perf Page. 

**To Reproduce**
Type in DEST and DEPT ICAOS using the new function of searching for them, go to perf page and selecting runway brings error unable to move from this position. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN 10
 - X-Plane version 11.36R2 
 - Version 

**Additional context**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/3721227/Log.txt)

**Comment by aeroniemi** [comment] 2019-10-12 22:31
duplicate of #122

**Closed by aeroniemi** 2019-10-12 22:31 UTC
Labels: duplicate
