### ISSUE TITLE
2 same buttons under Hydraulic on top panel.

### ISSUE THREAD

**Issue by DJ-STRE** [magknight/787aviatorsTracker#501] opened 2020-11-19 17:52 UTC
**Describe the bug**
Both buttons showing Right engine instead of Left and Right

**To Reproduce**

**Expected behavior**
Expected one to be Left and the other Right.

**Screenshots**
![image](https://user-images.githubusercontent.com/66440539/99704148-453db680-2a98-11eb-8761-b0e982c16125.png)
(Aimatures)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - X-Plane version [11.50]
 - Version [1.6.3]

**Comment by aeroniemi** [comment] 2020-11-19 17:53
duplicate of #490

**Closed by aeroniemi** 2020-11-19 17:53 UTC
Labels: triage
