### ISSUE TITLE
Captain's MFD Selector 

### ISSUE THREAD

**Issue by tailwest** [magknight/787aviatorsTracker#433] opened 2020-08-10 15:11 UTC
**Describe the bug**
1) COMM in the Captain's MFD selector does not change the captain's mfd to comm page
2) ENG on both Captain's and F/O MFD Selector does not remove the eng information from the MFD

**To Reproduce**
Click on ENG or COMM in the Captain's MFD Selector 

**Expected behavior**
1) Page should change to comm as like F/O comm
2) ENG additional information should go away in the EICAS, i.e oil temp.

**Screenshots**
![image](https://user-images.githubusercontent.com/62467289/89798150-81c25380-db34-11ea-98fd-7e7d39bc1281.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5b17
 - Version v1.6.0-cygnus5

**Comment by aeroniemi** [comment] 2020-08-10 16:02
partly duplicate of #424

**Comment by magknight1** [comment] 2020-08-10 21:23
Datarefs were assigned in place of the commands. Problem solved.

**Comment by aeroniemi** [comment] 2020-08-14 16:14
@magknight1 ND button command is wrong, should be aero787/cockpit/mfd/MFDcontrolsLeft/MFD1ND
EICAS button animation should be aero787/cockpit/mfd/MFDcontrols/MFDEICASswitchD (both sides)

**Comment by magknight1** [comment] 2020-08-26 02:34
Issues fixed.

**Closed** 2020-08-26 16:46 UTC
Labels: bug, fixed
