### ISSUE TITLE
Wind Direction and Speed not matching up with what ASXP says.

### ISSUE THREAD

**Issue by LiamMarkham** [magknight/787aviatorsTracker#454] opened 2020-08-13 15:41 UTC
**Describe the bug**
The wind speed and direction on the MFD does not change, it will stay as what it was when you loaded into the 787. On ActiveSky, the reported wind speed is 102/8, but the MFD says 250/2, has done the whole time. I also tried with the default weather, no difference, still 250/2. This has happened to me on a previous flight as well. 

It seems people are receiving the same issue in the new cockpit as well (I am in the old).

**To Reproduce**
No clue.

**Expected behavior**
I expect the wind speed and direction to match up with what ASXP says the wind speed and direction is.

**Screenshots**

![image](https://user-images.githubusercontent.com/69641039/90155470-436ea380-dd83-11ea-8b85-fe79c60a33e9.png)
![image](https://user-images.githubusercontent.com/69641039/90155510-51242900-dd83-11ea-8f0a-4454db5e7a50.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version: 11.50b1 (I think)
 - Version: 1.5.9

**Additional context**
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5069986/Log.txt)

**Comment by aeroniemi** [comment] 2020-08-14 21:02
duplicate of #453

**Closed by aeroniemi** 2020-08-14 21:02 UTC
Labels: triage
