### ISSUE TITLE
Still no nd and avitab on F/O seat

### ISSUE THREAD

**Issue by AeroChamzi** [magknight/787aviatorsTracker#747] opened 2022-03-08 20:22 UTC
**Describe the bug**
Still no magenta on nd track (even when nd is zoomed to 20nm), avitab on cpt seat (no issues) but no avitab on F/O seat

**To Reproduce**
-/-

**Expected behaviour**
Fixing issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.55r2]
 - Version [e.g. 1.7.33]

**Additional context**
-/-

**Comment by aeroniemi** [comment] 2022-03-08 22:33
Avitab is only supposed to be visible on the left side; ND fixed in 1.7.34 (duplicate of #743)

**Closed as completed by aeroniemi** 2022-03-08 22:33 UTC
Labels: duplicate
