### ISSUE TITLE
FLCH

### ISSUE THREAD

**Issue by tameraktasTU** [magknight/787aviatorsTracker#53] opened 2019-05-13 23:10 UTC
**Describe the bug**
FLCH still illuminates when not engaged

**To Reproduce**
just start sim and see FLCH engaged

**Expected behavior**
Should not be illuminated when not engaged
**Screenshots**
//

**Desktop (please complete the following information):**
 - Windows 10
 - X-Plane version 11.33
 - Version 1.2.1

**Additional context**

**Comment by aeroniemi** [comment] 2019-05-14 06:37
Duplicate of #48

**Closed by aeroniemi** 2019-05-14 06:37 UTC
Labels: 1.2.x-release
