### ISSUE TITLE
B788 still depicting B789 Runway Turnoff Lights when activated

### ISSUE THREAD

**Issue by oceanboi89** [magknight/787aviatorsTracker#814] opened 2022-04-21 01:54 UTC
Please refer to the picture. The Runway Turnoff Light is highlighted in Yellow.
![Screenshot (42)](https://user-images.githubusercontent.com/98982429/164356138-f74e1490-649f-4e38-a0b8-1c6223b448e6.jpg)

**Comment by aeroniemi** [comment] 2022-04-22 11:17
it looks like the issue is actually that there's two runway turnoff lights

**Comment by aeroniemi** [comment] 2022-04-22 12:12
Fixed in 1.7.50

**Closed as completed by aeroniemi** 2022-04-22 12:12 UTC
Labels: bug
