### ISSUE TITLE
Electrics V2?

### ISSUE THREAD

**Issue by mrmcnuggetboi** [magknight/787aviatorsTracker#413] opened 2020-08-01 02:01 UTC
**Is your feature request related to a problem? Please describe.**
To me the APU/GPU doesn't seem to do anything when you turn on the battery it turns everything on while it should only turn on the EICAS and the 2 CDU's as seen in this picture https://prnt.sc/ts3dob

**Describe the solution you'd like*
I suggest the Devs update the electric systems so when you turn on the battery it only turns on the ND and CDU's after about 1 min to 90 seconds and you need GND PWR or APU power to turn on the other screens and lights. Also will IRS logic be added when the new FMC arrives where you have to add the GPS pos in the FMC before the ND and PFD become normal from the https://prnt.sc/to6j9x non aligned state seen here.

**Describe alternatives you've considered**
At least make a IRS not aligned texture for the PFD 
**Additional context**
N/A

**Comment by aeroniemi** [comment] 2020-10-22 12:54
duplicate of magknight/787#131

**Closed** 2020-10-22 12:55 UTC
Labels: enhancement, triage
