### ISSUE TITLE
TCAS bug

### ISSUE THREAD

**Issue by ItzJohnny** [magknight/787aviatorsTracker#146] opened 2019-10-13 17:06 UTC
**Describe the bug**

I will move my throttles up, and when I move them back down to Idle and I get a TCAS TEST FAIL warning over the GPWS

**To Reproduce**

Move throttles up as far forward and move back to idle or lowest throttle setting without reverse thrust enabled.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.30r2]
 - Version [e.g. 1.2.0B1]

**Additional context**

This bug occurs with my Logitech/Saitek throttle quadrant.

**Comment by aeroniemi** [comment] 2019-10-13 19:54
likely a duplicate of #126

**Closed by aeroniemi** 2019-10-13 19:54 UTC
Labels: bug, duplicate
