### ISSUE TITLE
HUD glass misaligned - Beta 3

### ISSUE THREAD

**Issue by DeltaYankee2** [magknight/787aviatorsTracker#166] opened 2019-10-18 11:09 UTC
**Describe the bug**
The HUD glass is out of place
![787 HUD](https://user-images.githubusercontent.com/56453879/67089629-07d56e00-f1a0-11e9-9907-ca3829f2c2e2.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - X-Plane version [e.g. 11.36r2]
 - Version [e.g. 1.2.0B3]

**Additional context**

**Comment by aeroniemi** [comment] 2019-10-18 12:40
duplicate of #123

**Closed** 2019-10-18 12:42 UTC
Labels: bug, duplicate
