### ISSUE TITLE
liverySettings.json file and Custom soundpack Issue.

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#293] opened 2020-03-02 20:02 UTC
**Describe the bug**
When starting a flight the liverySettings.json from the livery folder isn't loading.
Instead, the default settings get loaded.
It only gets loaded after reload the Aircraft with the developer menu.
But the custom soundpack will not get loaded.
Also, when changing livery, you must again reload the aircraft so the new liverySettings.json will get loaded.

**To Reproduce**
Start a flight with the Magknight and look if the liverySettings.json gets loaded from start.
Create a custom soundpack and try to get it loaded.

**Expected behavior**
The liverySettings.json should get loaded initial when loading the Aircraft.
Custom soundpacks should get recogniced.

**Screenshots**
![soundpack](https://user-images.githubusercontent.com/56799893/75712234-ecd74680-5cc7-11ea-9b4d-66bbcecd49fb.jpg)

**Video**
https://youtu.be/P3R7F1A5Lj0

**files**
FlyAustria liverySettings.json:
[FlyAustria_liverySettings.zip](https://github.com/magknight/787aviatorsTracker/files/4277594/FlyAustria_liverySettings.zip)

BOAC:
[BOAC_liverySettings.zip](https://github.com/magknight/787aviatorsTracker/files/4277601/BOAC_liverySettings.zip)

XP11 LOG:
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/4277604/Log.txt)

**Desktop (please complete the following information):**
- OS: Windows 10
- X-Plane version 11.41r1
- Version 1.4.4

**Additional context**
This is similar to the #291 Issue!

**Comment by aeroniemi** [comment] 2020-03-08 11:36
duplicate of #291

**Closed by aeroniemi** 2020-03-08 11:36 UTC
Labels: triage
