### ISSUE TITLE
Inboard Display/Contrast for FIRST OFFICER

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#441] opened 2020-08-11 02:55 UTC
**Describe the bug**
Inboard display/contrast switch for FIRST OFFICER not working. 

**To Reproduce**
Try to turn the brightness down. It does not work. 

**Expected behavior**
Should allow the user to change the brightness of the screen. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane 11.5
 - Version 1.6

**Comment by aeroniemi** [comment] 2020-08-11 08:34
duplicate of #422

**Closed by aeroniemi** 2020-08-11 08:34 UTC
Labels: triage
