### ISSUE TITLE
Packs Will Not Operate On Ground Power

### ISSUE THREAD

**Issue by Viper787** [magknight/787aviatorsTracker#252] opened 2020-01-08 14:04 UTC
**Describe the bug**
On pre-flight w/ground power connected Packs will not operate. They will only operate w/APU running, or of course after engine start and generators running.

**To Reproduce**
Turn on Battery, Request Ground Power and make available. You should be able to start packs at this point.

**Expected behavior**
With ground power running, you should be able to start the packs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs 10.12.6
 - X-Plane version 11.41r1
 - Version 1.4.0 RC-3

**Additional context**

**Comment by aeroniemi** [comment] 2020-01-19 13:12
duplicate of #240

**Closed by aeroniemi** 2020-01-19 13:12 UTC
Labels: bug, duplicate
