### ISSUE TITLE
The logo lamp position of the 787-8 is incorrect

### ISSUE THREAD

**Issue by niu2571** [magknight/787aviatorsTracker#760] opened 2022-03-12 09:36 UTC
The logo light position of the 787-8 are in the incorrect place
![X-System 2022_3_12 11_47_48](https://user-images.githubusercontent.com/101453288/158012703-7a3a85eb-e6c6-4131-8b14-621bf5693d09.png)

**Comment by aeroniemi** [comment] 2022-03-13 23:56
duplicate of #735

**Closed as completed by aeroniemi** 2022-03-13 23:56 UTC
Labels: duplicate
