### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by wiktoro865** [magknight/787aviatorsTracker#436] opened 2020-08-10 17:32 UTC
When switching to the EFB perf. landing page. GPU/CPU usage drops and FPS's are dropping too.

**To Reproduce**
Enter the EFB landing

**Expected behavior**
No FPS drop or other weird performance issues.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Win 10
 - X-Plane version [e.g. 11.42]
 - Version [e.g. 1.6 - cygnus]

**Comment by aeroniemi** [comment] 2020-08-10 17:35
log?

**Comment by wiktoro865** [comment] 2020-08-10 17:45
[Log.txt](https://github.com/magknight/787aviatorsTracker/files/5052408/Log.txt)

**Comment by aeroniemi** [comment] 2020-08-10 21:40
duplicate of #412

**Closed by aeroniemi** 2020-08-10 21:40 UTC
Labels: triage
