### ISSUE TITLE
Rolls Royce engines unavailable.

### ISSUE THREAD

**Issue by Hazza7700** [magknight/787aviatorsTracker#419] opened 2020-08-10 10:03 UTC
If you select the RR engines option within the EFB and reload the aircraft the engines remain as the GE's. This also occurs if you are using a livery that will force the 787 to loading the RR engines.

**Comment by aeroniemi** [comment] 2020-08-10 10:22
likely an ACF merge issue

**Comment by aeroniemi** [comment] 2020-08-10 10:22
duplicate of #420

**Closed by aeroniemi** 2020-08-10 10:22 UTC
Labels: bug
