### ISSUE TITLE
Strobe sequence wrong

### ISSUE THREAD

**Issue by YYZatcboy** [magknight/787aviatorsTracker#190] opened 2019-10-24 09:13 UTC
**Describe the bug**
The strobes regularly short flash instead of the long LED pulse. It's more like an airbus than a 787. For note of how the LED strobes are supposed to be, check out the zibo LED strobe option.

**Comment by aeroniemi** [comment] 2019-10-24 11:08
They're doing both in the current release copy as the default ones are on unintentionally

**Comment by aeroniemi** [comment] 2019-10-24 11:13
duplicate of #111

**Closed by aeroniemi** 2019-10-24 11:13 UTC
Labels: bug
