### ISSUE TITLE
Aero787 SASL Bug

### ISSUE THREAD

**Issue by nvchris775** [magknight/787aviatorsTracker#452] opened 2020-08-12 20:22 UTC
Found when updated, buttons do not work. I performed a clean install and updated to 1.5.1 then updated config files and updated to 1.6 with no problems. I did not load the plane until it was completed as outlined in discord. I started to see if something was able to worked around and first started cold/dark, then with engines on. The displays would not work so I checked with the plugins and was playing around to see if I could get something to work and turning off Aero787 SASL brought up heading display but nothing else, when i turned it back on, the HSI flickered and then went black. i have attached screenshots and a portion of my log as it amassed over 60 mb in just the short time of taking screenshots and trying to get it to load up. 
[Slimmed down X-Plane Log.txt](https://github.com/magknight/787aviatorsTracker/files/5065459/Slimmed.down.X-Plane.Log.txt)
[Magnight Bug.docx](https://github.com/magknight/787aviatorsTracker/files/5065465/Magnight.Bug.docx)

**Comment by aeroniemi** [comment] 2020-08-12 20:26
duplicate of #415

**Closed by aeroniemi** 2020-08-12 20:26 UTC
Labels: triage
