### ISSUE TITLE
Avitab on F/O seat

### ISSUE THREAD

**Issue by AeroChamzi** [magknight/787aviatorsTracker#754] opened 2022-03-09 16:17 UTC
**Is your feature request related to a problem? Please describe.**
Please if it is possible to add an avitab by the officer seat 

**Describe the solution you'd like**
Avitab on both sides

**Describe alternatives you've considered**

**Additional context**

**Comment by AeroChamzi** [comment] 2022-03-09 16:19
duplicate

**Comment by Simleybob** [comment] 2022-03-10 07:53
#611

**Comment by aeroniemi** [comment] 2022-03-11 18:36
duplicate of #611

**Closed as completed by aeroniemi** 2022-03-11 18:36 UTC
Labels: duplicate, enhancement
