### ISSUE TITLE
Passenger cabin textures issues

### ISSUE THREAD

**Issue by gusram5** [magknight/787aviatorsTracker#746] opened 2022-03-08 20:14 UTC
**Describe the bug**
The pax cabin texture has several issues: too much alpha channel, missing floor, windows blocked.

![B788 - 2022-03-08 11 45 47](https://user-images.githubusercontent.com/101215086/157317465-4339a968-15c3-484c-84da-391a6724cc23.png)

![B788 - 2022-03-08 11 45 45](https://user-images.githubusercontent.com/101215086/157317471-8a6ee077-0bee-4bef-bc17-8c3f0394b86a.png)
![B788 - 2022-03-08 11 46 13](https://user-images.githubusercontent.com/101215086/157317494-d7f74cbc-5474-4e5e-8779-b0c52e96fa3f.png)

**Comment by aeroniemi** [comment] 2022-03-08 22:34
floor issue is duplicate of #732 
windows is duplicate of #734, fixed in 1.7.33

**Closed as completed by aeroniemi** 2022-03-08 22:34 UTC
Labels: duplicate
