### ISSUE TITLE
Radio volume switches not working. 

### ISSUE THREAD

**Issue by basespl1tyt** [magknight/787aviatorsTracker#444] opened 2020-08-11 03:06 UTC
**Describe the bug**
Radio volume switches for VHF, HF, etc... radios not working. 

**To Reproduce**
Try to turn on/off the radios and change the volume. 
This is problematic since, many are unable to fly on VATSIM from not being able 

**Expected behavior**
Should allow pilot to change radios and volume. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.5
 - Version 1.6

**Comment by aeroniemi** [comment] 2020-08-11 08:34
duplicate of FR #423

**Closed by aeroniemi** 2020-08-11 08:34 UTC
Labels: triage
