### ISSUE TITLE
ILS LOC doesn´t hold Center

### ISSUE THREAD

**Issue by KBNOtaku** [magknight/787aviatorsTracker#200] opened 2019-10-26 19:54 UTC
**Describe the bug**
On an ILS approach the LOC starts to offcenter from around 1500ft over ground and dont hold center any more.
When centering the Aircraft manuel and then activate LOC again, The Aircraft again fly´s off center?
Tried in a few scenerys and Airports, alway´s the same problem?

**To Reproduce**
Fly an ILS approach

**Expected behavior**
Aircraft should hold center until deactivating A/P

**Video**
https://youtu.be/VhtSbPVcgqg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.36r2
 - Version 1.4 Beta5

**Comment by aeroniemi** [comment] 2019-10-29 23:55
duplicate of #152

**Closed by aeroniemi** 2019-10-29 23:55 UTC
Labels: triage
