### ISSUE TITLE
Autopilot disengage Button inverted

### ISSUE THREAD

**Issue by majorleonb** [magknight/787aviatorsTracker#112] opened 2019-10-04 21:19 UTC
Autopilot disengage Button inverted, Autopilot only working when Button disengaged (pulled down)

Should be up for operations and pulled down for disengagement

OS: Windows 10 Pro
X-Plane version: XP 11.36r2, build 113601 64-bit, experimental flight model
Version 1.4.0-devBeta2

**Comment by aeroniemi** [comment] 2019-10-05 13:42
duplicate of #105

**Closed by aeroniemi** 2019-10-05 13:42 UTC
Labels: triage
